### ISSUE TITLE
CTF

### ISSUE THREAD

**Issue by d3vn0mi** [crond-jaist/cytrone#2]
Hello, 
Do you have any guidelines on how to setup the CTF scenario from https://www.jaist.ac.jp/misc/crond/achievements-en.html? 
I am trying but without success.
Thanks,
Iason

**Comment by crond-jaist** [comment]
Hi,

The `ctf-1.1.tgz` archive contains a `README.md` file with setup instructions:
* First you need to install CyTrONE and the related modules; if you haven't done this already, please follow the instructions on the CyTrONE GitHub page. 
* Next you need to install the CTF training content in CyTrONE; the procedure for this is described in the section "Setup" of the `README.md` file mentioned above.
If you still have issues please provide more details about the kind of troubles you encounter.

Best wishes,
Razvan

**Comment by d3vn0mi** [comment]
Hi,
thank you for your response.
I have installed and configured the sub components (Cyris, Cylms, Cyprom) and I checked that they work by running them individually as described in their .docs.
I have install and configured Cytrone and i can start and create a session with the given examples incl. NIST-1. I can then navigate to the :8081 and interact with the training material. The instantiation of the scenario was completed with no errors.

Now I wish to run the ctf-1.1 scenario, I followed the readme but I dont know how to deal with 'Update the Cytrone training database ...." . I have updated the **training-en.yml** with the values from the **ctf/training-en.yml.ctf**  see below for my final training-en.yml. Now, I try to run the  create_session script but I am presented with the same options as previously. Upon investigating the create_session script i see that these options are hard-coded.

So my question is basically this, do I need to change something on that script to include the new training content? or did i miss something?
Thank you,
Iason

```
---
# Description of the types of training available in the database
- types:
  - name: Scenario-Based Training
    category: scenarios
  - name: Topic-Based Training [N/A]
    category: topics

# Description of the scenarios available in the training database
- scenarios:

  # Content inspired by the U.S. NIST "Technical Guide to Information
  # Security Testing and Assessment"
  - name: Information Security Testing and Assessment
    levels:
      - name: Level 1
        content: NIST-level1-content-en.yml
        range: NIST-level1-range.yml
      - name: Level 2 [N/A]
  - name: CTF-style content
    levels:
      - name: Binary
        content: ctf/binary/binary-content-en.yml
        specification: ctf/binary/binary-range.yml
      - name: Cryptography
        content: ctf/crypto/crypto-content-en.yml
        specification: ctf/crypto/crypto-range.yml
      - name: Network
        content: ctf/network/network-content-en.yml
        specification: ctf/network/network-range.yml
      - name: Operating System
        content: ctf/os/os-content-en.yml
        specification: ctf/os/os-range.yml
      - name: Web
        content: ctf/web/web-content-en.yml
        specification: ctf/web/web-range.yml
```
